## ![](https://ga-dash.s3.amazonaws.com/production/assets/logo-9f88ae6c9c3871690e33280fcf557f33.png) Project 3: NLP Classification: Subreddit Pepsi vs Coca-Cola | Part 2: Vectorizer

---

[README](../README.md) | [Part 1: EDA](01_EDA.ipynb) | **Part 2: Vectorizer** | [Part 3: xxx](03_Interpretation.ipynb)

---

### Introduction
From [Part 1: EDA](01_EDA.ipynb), we obtained `subreddit_pepsi_vs_cocacola.csv_clean`, which has been cleaned. In this part, we focus on tuning the hyperparameters of two vectorizers: **CountVectorizer** and **TfidfVectorizer**, while using default settings for the model. Our goal is to analyze how the hyperparameters of the vectorizers affect model performance.

The **CountVectorizer** represents each document by the frequency of words (tokens) in the text. While **TfidfVectorizer** measures the relative importance of a word in a document by balancing its frequency in that document (Term Frequency) with how rare it is across all documents (Inverse Document Frequency). The latter vectorizer often provides better results, especially when distinguishing key terms in large corpora.

### Import

In [5]:
# Data manipulation and plotting
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# NLP tools
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, RegexpTokenizer
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Model selection and evaluation
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import make_scorer, accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Classifiers
from sklearn.naive_bayes import MultinomialNB 
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

# Time utility
import time
from joblib import parallel_backend

# Set seed for reproducibility
np.random.seed(42)

### Data Preparation

In [7]:
df = pd.read_csv('../data/subreddit_pepsi_vs_cocacola_clean.csv')          # Load Data
df.head(1)                                                                 # Check first row

,title,score,id,url,comms_num,created,body,is_pepsi,title_body,title_body_length,title_body_word_count
0,Wall clock.,17,1godhom,https://www.reddit.com/gallery/1godhom,1,11/11/2024 5:58,I'm trying to locate a value for this clock. I...,0,Wall clock. I'm trying to locate a value for t...,220,39

In [8]:
df.shape

(1958, 11)

In [9]:
# Set Features and Target

X = df['title_body']
y = df['is_pepsi']

# Split the data to training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X
                                                    , y
                                                    , test_size = 0.2
                                                    , stratify = y
                                                   )

### Vectorizer
- We focus on two types of vectorizers: **CountVectorizer** and **TfidfVectorizer**, which share the same set of parameters.
- First, converting the text to lowercase and removing words related to **Pepsi** and **Coca-Cola** are mandatory steps.
- The other parameters we will adjust for comparison are:
    - Removes English Stopwords or not
    - Maximum features: 3000, 5000, or None
    - N-gram length: whether to include bigrams or not
    - Minimum document frequency (min_df): 2, or 3
    - Maximum document frequency (max_df): 0.8 or 0.9

In [11]:
# Related words are words that can easily identify the subreddit categories, 
# such as the names of brands.
related_words = {'pepsi', 'pepsico', 'coca', 'cola', 'coke'}

# Custom stop words are common English words that are meaningless, 
# and we also include related words to create a custom stop word list.

custom_stop_words = set(stopwords.words('english')).union(related_words)

In [12]:
# Instantiate Stemmer and Lemmatizer
stemmer = nltk.PorterStemmer()
lemmatizer = nltk.WordNetLemmatizer()

# Create 6 custom tokenizers. 
# Note that all tokenizers are designed to remove symbols, related words, and convert text to lowercase, 
# with the following additional functions:
# - lower_only: no other changes
# - lower_stop: removes stopwords
# - stem_only: applies stemming
# - stem_stop: applies stemming and removes stopwords
# - lem_only: applies lemmatizing
# - lem_stop: applies lemmatizing and removes stopwords

def lower_only(doc):
    doc = doc.lower()
    tokens = word_tokenize(doc)
    return [token for token in tokens if token not in related_words and token.isalpha()]

def lower_stop(doc):
    doc = doc.lower()
    tokens = word_tokenize(doc)
    return [token for token in tokens if token not in custom_stop_words and token.isalpha()]

def stem_only(doc):
    doc = doc.lower()
    tokens = word_tokenize(doc)
    return [stemmer.stem(token) for token in tokens if token not in related_words and token.isalpha()]

def stem_stop(doc):
    doc = doc.lower()
    tokens = word_tokenize(doc)
    return [stemmer.stem(token) for token in tokens if token not in custom_stop_words and token.isalpha()]

def lem_only(doc):
    doc = doc.lower()
    tokens = word_tokenize(doc)
    return [lemmatizer.lemmatize(token) for token in tokens if token not in related_words and token.isalpha()]

def lem_stop(doc):
    doc = doc.lower()
    tokens = word_tokenize(doc)
    return [lemmatizer.lemmatize(token) for token in tokens if token not in custom_stop_words and token.isalpha()]

In [13]:
# Custom metrics used in GridSearch results
scorers = {
    'accuracy': make_scorer(accuracy_score)
    , 'recall': make_scorer(recall_score, average = 'binary')
    , 'precision': make_scorer(precision_score, average = 'binary')
    , 'f1': make_scorer(f1_score, average = 'binary')
}

In [14]:
# GridSearch parameters
# 'vectorizer__' is used to set parameters for CountVectorizer and TfidfVectorizer.
# Since the tokenizer parameter is applied, we set 'token_pattern' to None.
params = {
    'vectorizer': [CountVectorizer(token_pattern = None)
                   , TfidfVectorizer(token_pattern = None)
                  ] 
    , 'vectorizer__tokenizer': [lower_only
                                , lower_stop
                                , stem_only
                                , stem_stop
                                , lem_only
                                , lem_stop
                               ] 
    , 'vectorizer__max_features': [3000
                                   , 5000
                                   , None
                                  ]
    , 'vectorizer__ngram_range': [(1, 1)                  # unigrams
                                  , (1, 2)                # unigrams and bigrams
                                 ]
    , 'vectorizer__min_df': [2, 3]
    , 'vectorizer__max_df': [0.8, 0.9]
    , 'classifier': [#MultinomialNB()
                     #, LogisticRegression()
                     #, KNeighborsClassifier()
                     #, DecisionTreeClassifier()
                     #, BaggingClassifier()
                     #, RandomForestClassifier()
                      AdaBoostClassifier(algorithm = 'SAMME')
                     #, GradientBoostingClassifier()
                     #, SVC()
                     #, XGBClassifier()
                    ]
}

In [15]:
# Create Pipeline
pipeline = Pipeline([
    ('vectorizer', CountVectorizer())                    # Will replace in GridSearch  
    , ('classifier', MultinomialNB())                    # Will replace in GridSearch 
])

In [16]:
# GridSearchCV
grid_search = GridSearchCV(pipeline
                           , param_grid=params
                           , cv = 5
                           , verbose = 3
                           , scoring = scorers
                           , refit = 'f1'
                           , return_train_score = True
)

In [17]:
# Fit the grid search

# Record start time
start_time =time.time()



with parallel_backend('threading', n_jobs=-1):
    grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 288 candidates, totalling 1440 fits
[CV 3/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lower_stop at 0x0000022EDAEEE160>; accuracy: (train=0.601, test=0.559) f1: (train=0.718, test=0.695) precision: (train=0.560, test=0.536) recall: (train=0.998, test=0.987) total time=  11.2s
[CV 1/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lower_stop at 0x0000022EDAEEE160>; accuracy: (train=0.641, test=0.605) f1: (train=0.725, test=0.700) precision: (train=0.594, test=0.571) recall: (train=0.931, test=0.906) total time=  11.8s
[CV 2/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lower_stop at 0x0000022EDAEEE160>; accuracy: (train=0.630, test=0.633) f1: (train=0.721, test=0.726) precision: (train=0.584, test=0.585) recall: (train=0.940, test=0.956) total time=  12.7s
[CV 3/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lower_only at 0x0000022EDD5C1E40>; accuracy: (train=0.601, test=0.559) f1: (train=0.718, test=0.695) precision: (train=0.560, test=0.536) recall: (train=0.998, test=0.987) total time=  12.7s
[CV 4/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lower_only at 0x0000022EDD5C1E40>; accuracy: (train=0.619, test=0.610) f1: (train=0.721, test=0.715) precision: (train=0.575, test=0.569) recall: (train=0.967, test=0.962) total time=  14.0s
[CV 1/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lower_only at 0x0000022EDD5C1E40>; accuracy: (train=0.641, test=0.605) f1: (train=0.725, test=0.700) precision: (train=0.594, test=0.571) recall: (train=0.931, test=0.906) total time=  13.5s
[CV 5/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lower_only at 0x0000022EDD5C1E40>; accuracy: (train=0.648, test=0.610) f1: (train=0.730, test=0.704) precision: (train=0.598, test=0.573) recall: (train=0.937, test=0.912) total time=  16.3s
[CV 2/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lower_only at 0x0000022EDD5C1E40>; accuracy: (train=0.630, test=0.633) f1: (train=0.721, test=0.726) precision: (train=0.584, test=0.585) recall: (train=0.940, test=0.956) total time=  14.1s
[CV 4/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lower_stop at 0x0000022EDAEEE160>; accuracy: (train=0.620, test=0.610) f1: (train=0.722, test=0.715) precision: (train=0.575, test=0.569) recall: (train=0.969, test=0.962) total time=  18.2s
[CV 5/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lower_stop at 0x0000022EDAEEE160>; accuracy: (train=0.630, test=0.610) f1: (train=0.722, test=0.710) precision: (train=0.584, test=0.571) recall: (train=0.945, test=0.937) total time=  22.1s
[CV 1/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function stem_stop at 0x0000022EDAEEFCE0>; accuracy: (train=0.685, test=0.659) f1: (train=0.735, test=0.716) precision: (train=0.642, test=0.622) recall: (train=0.860, test=0.844) total time=  18.1s
[CV 2/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function stem_only at 0x0000022EDAEEF380>; accuracy: (train=0.652, test=0.681) f1: (train=0.722, test=0.746) precision: (train=0.608, test=0.626) recall: (train=0.889, test=0.925) total time=  22.4s
[CV 5/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function stem_only at 0x0000022EDAEEF380>; accuracy: (train=0.679, test=0.645) f1: (train=0.733, test=0.710) precision: (train=0.635, test=0.607) recall: (train=0.867, test=0.855) total time=  21.4s
[CV 3/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function stem_only at 0x0000022EDAEEF380>; accuracy: (train=0.637, test=0.604) f1: (train=0.725, test=0.699) precision: (train=0.590, test=0.569) recall: (train=0.940, test=0.906) total time=  22.3s
[CV 4/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function stem_only at 0x0000022EDAEEF380>; accuracy: (train=0.634, test=0.623) f1: (train=0.722, test=0.716) precision: (train=0.588, test=0.580) recall: (train=0.936, test=0.937) total time=  24.0s
[CV 1/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function stem_only at 0x0000022EDAEEF380>; accuracy: (train=0.685, test=0.659) f1: (train=0.735, test=0.716) precision: (train=0.642, test=0.622) recall: (train=0.860, test=0.844) total time=  25.6s
[CV 2/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lem_only at 0x0000022EDAEEF880>; accuracy: (train=nan, test=nan) f1: (train=nan, test=nan) precision: (train=nan, test=nan) recall: (train=nan, test=nan) total time=  11.1s
[CV 1/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lem_only at 0x0000022EDAEEF880>; accuracy: (train=nan, test=nan) f1: (train=nan, test=nan) precision: (train=nan, test=nan) recall: (train=nan, test=nan) total time=  11.2s
[CV 3/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lem_only at 0x0000022EDAEEF880>; accuracy: (train=nan, test=nan) f1: (train=nan, test=nan) precision: (train=nan, test=nan) recall: (train=nan, test=nan) total time=  10.6s
[CV 2/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function stem_stop at 0x0000022EDAEEFCE0>; accuracy: (train=0.652, test=0.681) f1: (train=0.722, test=0.746) precision: (train=0.608, test=0.626) recall: (train=0.889, test=0.925) total time=  25.0s
[CV 3/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function stem_stop at 0x0000022EDAEEFCE0>; accuracy: (train=0.637, test=0.604) f1: (train=0.725, test=0.699) precision: (train=0.590, test=0.569) recall: (train=0.940, test=0.906) total time=  22.3s
[CV 4/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function stem_stop at 0x0000022EDAEEFCE0>; accuracy: (train=0.634, test=0.623) f1: (train=0.722, test=0.716) precision: (train=0.588, test=0.580) recall: (train=0.936, test=0.937) total time=  25.5s
[CV 5/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function stem_stop at 0x0000022EDAEEFCE0>; accuracy: (train=0.674, test=0.645) f1: (train=0.729, test=0.709) precision: (train=0.631, test=0.608) recall: (train=0.863, test=0.849) total time=  25.8s
[CV 2/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lem_stop at 0x0000022EDAEEF6A0>; accuracy: (train=0.623, test=0.645) f1: (train=0.716, test=0.734) precision: (train=0.580, test=0.593) recall: (train=0.936, test=0.962) total time=  18.1s
[CV 1/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lem_stop at 0x0000022EDAEEF6A0>; accuracy: (train=0.664, test=0.627) f1: (train=0.731, test=0.702) precision: (train=0.615, test=0.592) recall: (train=0.901, test=0.863) total time=  18.9s
[CV 4/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lem_only at 0x0000022EDAEEF880>; accuracy: (train=0.629, test=0.617) f1: (train=0.720, test=0.713) precision: (train=0.584, test=0.575) recall: (train=0.940, test=0.937) total time=  31.7s
[CV 5/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lem_only at 0x0000022EDAEEF880>; accuracy: (train=0.651, test=0.626) f1: (train=0.726, test=0.711) precision: (train=0.605, test=0.585) recall: (train=0.907, test=0.906) total time=  21.2s
[CV 3/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lem_stop at 0x0000022EDAEEF6A0>; accuracy: (train=0.632, test=0.597) f1: (train=0.723, test=0.696) precision: (train=0.586, test=0.565) recall: (train=0.945, test=0.906) total time=  15.9s
[CV 4/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lem_stop at 0x0000022EDAEEF6A0>; accuracy: (train=0.629, test=0.617) f1: (train=0.720, test=0.713) precision: (train=0.584, test=0.575) recall: (train=0.940, test=0.937) total time=  15.5s
[CV 5/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 1), vectorizer__tokenizer=<function lem_stop at 0x0000022EDAEEF6A0>; accuracy: (train=0.658, test=0.645) f1: (train=0.725, test=0.719) precision: (train=0.613, test=0.602) recall: (train=0.889, test=0.893) total time=  11.8s
[CV 1/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function lower_only at 0x0000022EDD5C1E40>; accuracy: (train=0.641, test=0.605) f1: (train=0.725, test=0.700) precision: (train=0.594, test=0.571) recall: (train=0.931, test=0.906) total time=  14.1s
[CV 3/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function lower_only at 0x0000022EDD5C1E40>; accuracy: (train=0.601, test=0.559) f1: (train=0.718, test=0.695) precision: (train=0.560, test=0.536) recall: (train=0.998, test=0.987) total time=  15.3s
[CV 2/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function lower_only at 0x0000022EDD5C1E40>; accuracy: (train=0.645, test=0.633) f1: (train=0.729, test=0.724) precision: (train=0.596, test=0.585) recall: (train=0.939, test=0.950) total time=  16.2s
[CV 4/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function lower_only at 0x0000022EDD5C1E40>; accuracy: (train=0.619, test=0.610) f1: (train=0.721, test=0.715) precision: (train=0.575, test=0.569) recall: (train=0.967, test=0.962) total time=  15.5s
[CV 5/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function lower_only at 0x0000022EDD5C1E40>; accuracy: (train=0.648, test=0.610) f1: (train=0.730, test=0.704) precision: (train=0.598, test=0.573) recall: (train=0.937, test=0.912) total time=  16.0s
[CV 1/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function lower_stop at 0x0000022EDAEEE160>; accuracy: (train=0.641, test=0.605) f1: (train=0.725, test=0.700) precision: (train=0.594, test=0.571) recall: (train=0.931, test=0.906) total time=  20.4s
[CV 2/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function lower_stop at 0x0000022EDAEEE160>; accuracy: (train=0.630, test=0.633) f1: (train=0.721, test=0.726) precision: (train=0.584, test=0.585) recall: (train=0.940, test=0.956) total time=  21.6s
[CV 3/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function lower_stop at 0x0000022EDAEEE160>; accuracy: (train=0.601, test=0.559) f1: (train=0.718, test=0.695) precision: (train=0.560, test=0.536) recall: (train=0.998, test=0.987) total time=  19.4s
[CV 4/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function lower_stop at 0x0000022EDAEEE160>; accuracy: (train=0.620, test=0.610) f1: (train=0.722, test=0.715) precision: (train=0.575, test=0.569) recall: (train=0.969, test=0.962) total time=  21.7s
[CV 5/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function lower_stop at 0x0000022EDAEEE160>; accuracy: (train=0.630, test=0.610) f1: (train=0.722, test=0.710) precision: (train=0.584, test=0.571) recall: (train=0.945, test=0.937) total time=  22.9s
[CV 1/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function stem_only at 0x0000022EDAEEF380>; accuracy: (train=0.685, test=0.659) f1: (train=0.735, test=0.716) precision: (train=0.642, test=0.622) recall: (train=0.860, test=0.844) total time=  26.1s
[CV 3/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function stem_only at 0x0000022EDAEEF380>; accuracy: (train=0.637, test=0.604) f1: (train=0.725, test=0.699) precision: (train=0.590, test=0.569) recall: (train=0.940, test=0.906) total time=  25.3s
[CV 2/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function stem_only at 0x0000022EDAEEF380>; accuracy: (train=0.639, test=0.658) f1: (train=0.724, test=0.737) precision: (train=0.593, test=0.605) recall: (train=0.929, test=0.943) total time=  31.9s
[CV 4/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function stem_only at 0x0000022EDAEEF380>; accuracy: (train=0.634, test=0.623) f1: (train=0.722, test=0.716) precision: (train=0.588, test=0.580) recall: (train=0.936, test=0.937) total time=  31.8s
[CV 1/5] END classifier=AdaBoostClassifier(algorithm='SAMME'), vectorizer=CountVectorizer(token_pattern=None), vectorizer__max_df=0.8, vectorizer__max_features=3000, vectorizer__min_df=2, vectorizer__ngram_range=(1, 2), vectorizer__tokenizer=<function stem_stop at 0x0000022EDAEEFCE0>; accuracy: (train=0.685, test=0.659) f1: (train=0.735, test=0.716) precision: (train=0.642, test=0.622) recall: (train=0.860, test=0.844) total time=  29.5s

C:\Users\Home\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
3 fits failed out of a total of 1440.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Home\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Home\anaconda3\Lib\site-packages\sklearn\base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 471, in fit
    Xt = self._fit(X, y, routed_params)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 408, in _fit
    X, fitted_transformer = fit_transform_one_cached(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home\anaconda3\Lib\site-packages\joblib\memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 1303, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home\anaconda3\Lib\site-packages\sklearn\base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py", line 1389, in fit_transform
    vocabulary, X = self._count_vocab(raw_documents, self.fixed_vocabulary_)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py", line 1276, in _count_vocab
    for feature in analyze(doc):
                   ^^^^^^^^^^^^
  File "C:\Users\Home\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py", line 112, in _analyze
    doc = tokenizer(doc)
          ^^^^^^^^^^^^^^
  File "C:\Users\Home\AppData\Local\Temp\ipykernel_16984\3587977024.py", line 38, in lem_only
    return [lemmatizer.lemmatize(token) for token in tokens if token not in related_words and token.isalpha()]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home\anaconda3\Lib\site-packages\nltk\stem\wordnet.py", line 45, in lemmatize
    lemmas = wn._morphy(word, pos)
             ^^^^^^^^^^
  File "C:\Users\Home\anaconda3\Lib\site-packages\nltk\corpus\util.py", line 121, in __getattr__
    self.__load()
  File "C:\Users\Home\anaconda3\Lib\site-packages\nltk\corpus\util.py", line 95, in __load
    args, kwargs = self.__args, self.__kwargs
                   ^^^^^^^^^^^
AttributeError: 'WordNetCorpusReader' object has no attribute '_LazyCorpusLoader__args'

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Home\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [0.60344722 0.60344722 0.64239026 0.64239026        nan 0.62643617
 0.60344722 0.60344722 0.63791742 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.64239026 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.63791742 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.64239026 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.63791742 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.64239026 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.63791742 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.64239026 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.63791742 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.64239026 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.63791742 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.64239026 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.63791742 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.64239026 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.63791742 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.64239026 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.63791742 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.64239026 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.63791742 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.64239026 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.63791742 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.64239026 0.64239026 0.62260231 0.62643617
 0.60344722 0.60344722 0.63791742 0.64239026 0.62260231 0.62643617
 0.61366069 0.61429967 0.65453084 0.6539     0.61877251 0.62195519
 0.60919599 0.61622678 0.64367432 0.65454101 0.61941556 0.62196943
 0.60536212 0.61877658 0.65197696 0.64942716 0.6117519  0.61366883
 0.61110885 0.6175027  0.64113062 0.65517185 0.61685761 0.62451721
 0.61366069 0.61429967 0.65453084 0.6539     0.61877251 0.62195519
 0.60280418 0.62068537 0.6436845  0.65326306 0.62132639 0.62069148
 0.60536212 0.61877658 0.65197696 0.64942716 0.61366883 0.61366883
 0.61301968 0.6175027  0.64560143 0.65517185 0.61239495 0.62451721
 0.61366069 0.61429967 0.65453084 0.6539     0.61877251 0.62195519
 0.6015364  0.62068537 0.64688346 0.65326306 0.62261045 0.62324739
 0.60536212 0.61877658 0.65197696 0.64942716 0.61366883 0.61366883
 0.61301968 0.6175027  0.64560143 0.65517185 0.60983903 0.62451721
 0.61366069 0.61429967 0.65453084 0.6539     0.61877251 0.62195519
 0.60919599 0.61622678 0.64367432 0.65454101 0.61941556 0.62196943
 0.60536212 0.61877658 0.65197696 0.64942716 0.61366883 0.61366883
 0.61110885 0.6175027  0.64113062 0.65517185 0.61685761 0.62451721
 0.61366069 0.61429967 0.65453084 0.6539     0.61877251 0.62195519
 0.60280418 0.62068537 0.6436845  0.65326306 0.62132639 0.62324739
 0.60536212 0.61877658 0.65197696 0.64942716 0.61366883 0.61366883
 0.61301968 0.6175027  0.64560143 0.65517185 0.60983903 0.62451721
 0.61366069 0.61429967 0.65453084 0.6539     0.61877251 0.62195519
 0.6015364  0.62068537 0.64688346 0.65326306 0.62261045 0.62324739
 0.60536212 0.61877658 0.65197696 0.64942716 0.61366883 0.61366883
 0.61301968 0.6175027  0.64560143 0.65517185 0.60983903 0.62451721]
  warnings.warn(
C:\Users\Home\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the train scores are non-finite: [0.62787572 0.62452376 0.65757148 0.65645416        nan 0.64096788
 0.63090844 0.62452376 0.65501761 0.65645416 0.64208519 0.64096788
 0.62787572 0.62452376 0.65757148 0.65645416 0.63969094 0.64096788
 0.63090844 0.62452376 0.65501761 0.65645416 0.64208519 0.64096788
 0.62787572 0.62452376 0.65757148 0.65645416 0.63969094 0.64096788
 0.63090844 0.62452376 0.65501761 0.65645416 0.64208519 0.64096788
 0.62787572 0.62452376 0.65757148 0.65645416 0.63969094 0.64096788
 0.63090844 0.62452376 0.65501761 0.65645416 0.64208519 0.64096788
 0.62787572 0.62452376 0.65757148 0.65645416 0.63969094 0.64096788
 0.63090844 0.62452376 0.65501761 0.65645416 0.64208519 0.64096788
 0.62787572 0.62452376 0.65757148 0.65645416 0.63969094 0.64096788
 0.63090844 0.62452376 0.65501761 0.65645416 0.64208519 0.64096788
 0.62787572 0.62452376 0.65757148 0.65645416 0.63969094 0.64096788
 0.63090844 0.62452376 0.65501761 0.65645416 0.64208519 0.64096788
 0.62787572 0.62452376 0.65757148 0.65645416 0.63969094 0.64096788
 0.63090844 0.62452376 0.65501761 0.65645416 0.64208519 0.64096788
 0.62787572 0.62452376 0.65757148 0.65645416 0.63969094 0.64096788
 0.63090844 0.62452376 0.65501761 0.65645416 0.64208519 0.64096788
 0.62787572 0.62452376 0.65757148 0.65645416 0.63969094 0.64096788
 0.63090844 0.62452376 0.65501761 0.65645416 0.64208519 0.64096788
 0.62787572 0.62452376 0.65757148 0.65645416 0.63969094 0.64096788
 0.63090844 0.62452376 0.65501761 0.65645416 0.64208519 0.64096788
 0.62787572 0.62452376 0.65757148 0.65645416 0.63969094 0.64096788
 0.63090844 0.62452376 0.65501761 0.65645416 0.64208519 0.64096788
 0.64543779 0.64032903 0.67704704 0.66171552 0.65341978 0.64767332
 0.64224545 0.63681312 0.67002223 0.6647499  0.6457523  0.63601338
 0.64032775 0.64240264 0.67816537 0.66443092 0.64320047 0.63617656
 0.64799293 0.63936686 0.66203705 0.6720984  0.64368175 0.64623651
 0.64543779 0.64032903 0.67704704 0.66171552 0.65341978 0.64767332
 0.63202436 0.64336238 0.66618722 0.66395182 0.64559269 0.63888648
 0.64032775 0.64240264 0.67816537 0.66443092 0.64351971 0.63617656
 0.64032507 0.63936686 0.66714467 0.6720984  0.64543689 0.64623651
 0.64543779 0.64032903 0.67704704 0.66171552 0.65310055 0.64767332
 0.64096635 0.64336238 0.66937969 0.66395182 0.65341952 0.63984418
 0.64032775 0.64240264 0.67816537 0.66443092 0.64351971 0.63617656
 0.64032507 0.63936686 0.66714467 0.6720984  0.64192532 0.64623651
 0.64543779 0.64032903 0.67704704 0.66171552 0.65341978 0.64767332
 0.64224545 0.63681312 0.67002223 0.6647499  0.6457523  0.63601338
 0.64032775 0.64240264 0.67816537 0.66443092 0.64351971 0.63617656
 0.64783332 0.63936686 0.66203705 0.6720984  0.64368175 0.64623651
 0.64543779 0.64032903 0.67704704 0.66171552 0.65341978 0.64767332
 0.63202436 0.64336238 0.66618722 0.66395182 0.64559269 0.63984418
 0.64032775 0.64240264 0.67816537 0.66443092 0.64351971 0.63617656
 0.64032507 0.63936686 0.66714467 0.6720984  0.64192532 0.64623651
 0.64543779 0.64032903 0.67704704 0.66171552 0.65310055 0.64767332
 0.64096635 0.64336238 0.66937969 0.66395182 0.65341952 0.63984418
 0.64032775 0.64240264 0.67816537 0.66443092 0.64351971 0.63617656
 0.64048469 0.63936686 0.66714467 0.6720984  0.64192532 0.64623651]
  warnings.warn(
C:\Users\Home\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [0.94477201 0.94980346 0.8932783  0.89202044        nan 0.91212264
 0.94351415 0.94980346 0.89705189 0.89202044 0.91212264 0.91212264
 0.94477201 0.94980346 0.8932783  0.89202044 0.91463836 0.91212264
 0.94351415 0.94980346 0.89705189 0.89202044 0.91212264 0.91212264
 0.94477201 0.94980346 0.8932783  0.89202044 0.91463836 0.91212264
 0.94351415 0.94980346 0.89705189 0.89202044 0.91212264 0.91212264
 0.94477201 0.94980346 0.8932783  0.89202044 0.91463836 0.91212264
 0.94351415 0.94980346 0.89705189 0.89202044 0.91212264 0.91212264
 0.94477201 0.94980346 0.8932783  0.89202044 0.91463836 0.91212264
 0.94351415 0.94980346 0.89705189 0.89202044 0.91212264 0.91212264
 0.94477201 0.94980346 0.8932783  0.89202044 0.91463836 0.91212264
 0.94351415 0.94980346 0.89705189 0.89202044 0.91212264 0.91212264
 0.94477201 0.94980346 0.8932783  0.89202044 0.91463836 0.91212264
 0.94351415 0.94980346 0.89705189 0.89202044 0.91212264 0.91212264
 0.94477201 0.94980346 0.8932783  0.89202044 0.91463836 0.91212264
 0.94351415 0.94980346 0.89705189 0.89202044 0.91212264 0.91212264
 0.94477201 0.94980346 0.8932783  0.89202044 0.91463836 0.91212264
 0.94351415 0.94980346 0.89705189 0.89202044 0.91212264 0.91212264
 0.94477201 0.94980346 0.8932783  0.89202044 0.91463836 0.91212264
 0.94351415 0.94980346 0.89705189 0.89202044 0.91212264 0.91212264
 0.94477201 0.94980346 0.8932783  0.89202044 0.91463836 0.91212264
 0.94351415 0.94980346 0.89705189 0.89202044 0.91212264 0.91212264
 0.94477201 0.94980346 0.8932783  0.89202044 0.91463836 0.91212264
 0.94351415 0.94980346 0.89705189 0.89202044 0.91212264 0.91212264
 0.89207547 0.9359827  0.84053459 0.89695755 0.85561321 0.90705975
 0.91090409 0.94346698 0.83926887 0.89446541 0.87811321 0.91955975
 0.9221305  0.93470912 0.85305818 0.89069182 0.89698113 0.92590409
 0.90336478 0.93842767 0.87565252 0.87944969 0.88202044 0.91209906
 0.89207547 0.9359827  0.84053459 0.89695755 0.85561321 0.90705975
 0.92841195 0.93346698 0.84799528 0.89320755 0.88062107 0.91955975
 0.9221305  0.93470912 0.85305818 0.89069182 0.89194969 0.92590409
 0.91709906 0.93842767 0.85049528 0.87944969 0.8794261  0.91209906
 0.89207547 0.9359827  0.84053459 0.89695755 0.85561321 0.90705975
 0.90334906 0.93346698 0.83417453 0.89320755 0.84683176 0.91830189
 0.9221305  0.93470912 0.85305818 0.89069182 0.89194969 0.92590409
 0.91709906 0.93842767 0.85049528 0.87944969 0.90206761 0.91209906
 0.89207547 0.9359827  0.84053459 0.89695755 0.85561321 0.90705975
 0.91090409 0.94346698 0.83926887 0.89446541 0.87811321 0.91955975
 0.9221305  0.93470912 0.85305818 0.89069182 0.89194969 0.92590409
 0.90336478 0.93842767 0.87565252 0.87944969 0.88202044 0.91209906
 0.89207547 0.9359827  0.84053459 0.89695755 0.85561321 0.90705975
 0.92841195 0.93346698 0.84799528 0.89320755 0.88062107 0.91830189
 0.9221305  0.93470912 0.85305818 0.89069182 0.89194969 0.92590409
 0.91709906 0.93842767 0.85049528 0.87944969 0.90206761 0.91209906
 0.89207547 0.9359827  0.84053459 0.89695755 0.85561321 0.90705975
 0.90334906 0.93346698 0.83417453 0.89320755 0.84683176 0.91830189
 0.9221305  0.93470912 0.85305818 0.89069182 0.89194969 0.92590409
 0.91709906 0.93842767 0.85049528 0.87944969 0.90206761 0.91209906]
  warnings.warn(
C:\Users\Home\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the train scores are non-finite: [0.95476635 0.95665018 0.89822922 0.89760128        nan 0.92210391
 0.95445238 0.95665018 0.90639248 0.89760128 0.92492965 0.92210391
 0.95476635 0.95665018 0.89822922 0.89760128 0.92587157 0.92210391
 0.95445238 0.95665018 0.90639248 0.89760128 0.92492965 0.92210391
 0.95476635 0.95665018 0.89822922 0.89760128 0.92587157 0.92210391
 0.95445238 0.95665018 0.90639248 0.89760128 0.92492965 0.92210391
 0.95476635 0.95665018 0.89822922 0.89760128 0.92587157 0.92210391
 0.95445238 0.95665018 0.90639248 0.89760128 0.92492965 0.92210391
 0.95476635 0.95665018 0.89822922 0.89760128 0.92587157 0.92210391
 0.95445238 0.95665018 0.90639248 0.89760128 0.92492965 0.92210391
 0.95476635 0.95665018 0.89822922 0.89760128 0.92587157 0.92210391
 0.95445238 0.95665018 0.90639248 0.89760128 0.92492965 0.92210391
 0.95476635 0.95665018 0.89822922 0.89760128 0.92587157 0.92210391
 0.95445238 0.95665018 0.90639248 0.89760128 0.92492965 0.92210391
 0.95476635 0.95665018 0.89822922 0.89760128 0.92587157 0.92210391
 0.95445238 0.95665018 0.90639248 0.89760128 0.92492965 0.92210391
 0.95476635 0.95665018 0.89822922 0.89760128 0.92587157 0.92210391
 0.95445238 0.95665018 0.90639248 0.89760128 0.92492965 0.92210391
 0.95476635 0.95665018 0.89822922 0.89760128 0.92587157 0.92210391
 0.95445238 0.95665018 0.90639248 0.89760128 0.92492965 0.92210391
 0.95476635 0.95665018 0.89822922 0.89760128 0.92587157 0.92210391
 0.95445238 0.95665018 0.90639248 0.89760128 0.92492965 0.92210391
 0.95476635 0.95665018 0.89822922 0.89760128 0.92587157 0.92210391
 0.95445238 0.95665018 0.90639248 0.89760128 0.92492965 0.92210391
 0.91485886 0.94659765 0.86933148 0.91081228 0.89037252 0.92461963
 0.92711215 0.95352033 0.86806819 0.91081277 0.90326412 0.93468795
 0.94377734 0.94566067 0.87939091 0.91143923 0.92556599 0.94472518
 0.92051578 0.94912473 0.89163631 0.89477948 0.90229802 0.92744686
 0.91485886 0.94659765 0.86933148 0.91081228 0.89037252 0.92461963
 0.93968682 0.94408588 0.87342446 0.91206866 0.90452001 0.93562987
 0.94377734 0.94566067 0.87939091 0.91143923 0.92179833 0.94472518
 0.92994974 0.94912473 0.8749958  0.89477948 0.91017347 0.92744686
 0.91485886 0.94659765 0.86933148 0.91081228 0.88974458 0.92461963
 0.93089363 0.94408588 0.86777544 0.91206866 0.87874717 0.93468795
 0.94377734 0.94566067 0.87939091 0.91143923 0.92179833 0.94472518
 0.92994974 0.94912473 0.8749958  0.89477948 0.92681398 0.92744686
 0.91485886 0.94659765 0.86933148 0.91081228 0.89037252 0.92461963
 0.92711215 0.95352033 0.86806819 0.91081277 0.90326412 0.93468795
 0.94377734 0.94566067 0.87939091 0.91143923 0.92179833 0.94472518
 0.92020181 0.94912473 0.89163631 0.89477948 0.90229802 0.92744686
 0.91485886 0.94659765 0.86933148 0.91081228 0.89037252 0.92461963
 0.93968682 0.94408588 0.87342446 0.91206866 0.90452001 0.93468795
 0.94377734 0.94566067 0.87939091 0.91143923 0.92179833 0.94472518
 0.92994974 0.94912473 0.8749958  0.89477948 0.92681398 0.92744686
 0.91485886 0.94659765 0.86933148 0.91081228 0.88974458 0.92461963
 0.93089363 0.94408588 0.86777544 0.91206866 0.87874717 0.93468795
 0.94377734 0.94566067 0.87939091 0.91143923 0.92179833 0.94472518
 0.93026372 0.94912473 0.8749958  0.89477948 0.92681398 0.92744686]
  warnings.warn(
C:\Users\Home\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [0.56664269 0.56619443 0.60074622 0.60093927        nan 0.58539766
 0.56677388 0.56619443 0.59660758 0.60093927 0.58242484 0.58539766
 0.56664269 0.56619443 0.60074622 0.60093927 0.58213185 0.58539766
 0.56677388 0.56619443 0.59660758 0.60093927 0.58242484 0.58539766
 0.56664269 0.56619443 0.60074622 0.60093927 0.58213185 0.58539766
 0.56677388 0.56619443 0.59660758 0.60093927 0.58242484 0.58539766
 0.56664269 0.56619443 0.60074622 0.60093927 0.58213185 0.58539766
 0.56677388 0.56619443 0.59660758 0.60093927 0.58242484 0.58539766
 0.56664269 0.56619443 0.60074622 0.60093927 0.58213185 0.58539766
 0.56677388 0.56619443 0.59660758 0.60093927 0.58242484 0.58539766
 0.56664269 0.56619443 0.60074622 0.60093927 0.58213185 0.58539766
 0.56677388 0.56619443 0.59660758 0.60093927 0.58242484 0.58539766
 0.56664269 0.56619443 0.60074622 0.60093927 0.58213185 0.58539766
 0.56677388 0.56619443 0.59660758 0.60093927 0.58242484 0.58539766
 0.56664269 0.56619443 0.60074622 0.60093927 0.58213185 0.58539766
 0.56677388 0.56619443 0.59660758 0.60093927 0.58242484 0.58539766
 0.56664269 0.56619443 0.60074622 0.60093927 0.58213185 0.58539766
 0.56677388 0.56619443 0.59660758 0.60093927 0.58242484 0.58539766
 0.56664269 0.56619443 0.60074622 0.60093927 0.58213185 0.58539766
 0.56677388 0.56619443 0.59660758 0.60093927 0.58242484 0.58539766
 0.56664269 0.56619443 0.60074622 0.60093927 0.58213185 0.58539766
 0.56677388 0.56619443 0.59660758 0.60093927 0.58242484 0.58539766
 0.56664269 0.56619443 0.60074622 0.60093927 0.58213185 0.58539766
 0.56677388 0.56619443 0.59660758 0.60093927 0.58242484 0.58539766
 0.57958692 0.57533873 0.61922844 0.60914707 0.5872196  0.58300339
 0.57413676 0.57594421 0.60932764 0.61001145 0.58473834 0.58171235
 0.57009294 0.5785912  0.61445632 0.60656815 0.57652354 0.57465949
 0.57635204 0.57696084 0.60090846 0.612904   0.58191117 0.58530432
 0.57958692 0.57533873 0.61922844 0.60914707 0.5872196  0.58300339
 0.56801047 0.58010584 0.60841822 0.60915126 0.58577387 0.58110313
 0.57009294 0.5785912  0.61445632 0.60656815 0.57897937 0.57465949
 0.57605883 0.57696084 0.60956722 0.612904   0.57934805 0.58530432
 0.57958692 0.57533873 0.61922844 0.60914707 0.5872196  0.58300339
 0.56948929 0.58010584 0.61430566 0.60915126 0.5910834  0.583562
 0.57009294 0.5785912  0.61445632 0.60656815 0.57897937 0.57465949
 0.57605883 0.57696084 0.60956722 0.612904   0.5740585  0.58530432
 0.57958692 0.57533873 0.61922844 0.60914707 0.5872196  0.58300339
 0.57413676 0.57594421 0.60932764 0.61001145 0.58473834 0.58171235
 0.57009294 0.5785912  0.61445632 0.60656815 0.57897937 0.57465949
 0.57635204 0.57696084 0.60090846 0.612904   0.58191117 0.58530432
 0.57958692 0.57533873 0.61922844 0.60914707 0.5872196  0.58300339
 0.56801047 0.58010584 0.60841822 0.60915126 0.58577387 0.583562
 0.57009294 0.5785912  0.61445632 0.60656815 0.57897937 0.57465949
 0.57605883 0.57696084 0.60956722 0.612904   0.5740585  0.58530432
 0.57958692 0.57533873 0.61922844 0.60914707 0.5872196  0.58300339

In [18]:
# Code you want to time (e.g., fitting a model)
# Example: grid_search.fit(X_train, y_train)

# Record end time
end_time = time.time()

# Calculate elapsed time
elapsed_time = end_time - start_time
print(f"Time taken: {elapsed_time:.4f} seconds")

Time taken: 5061.2015 seconds

In [19]:
# Collect results
cv_results = pd.DataFrame(grid_search.cv_results_)
cv_results.to_csv('../data/cv_results_ada.csv') 
# Display important metrics
cv_results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_classifier,param_vectorizer,param_vectorizer__max_df,param_vectorizer__max_features,param_vectorizer__min_df,param_vectorizer__ngram_range,...,mean_test_f1,std_test_f1,rank_test_f1,split0_train_f1,split1_train_f1,split2_train_f1,split3_train_f1,split4_train_f1,mean_train_f1,std_train_f1
0,10.350171,0.374434,3.880175,0.880687,AdaBoostClassifier(algorithm='SAMME'),CountVectorizer(token_pattern=None),0.8,3000,2,"(1, 1)",...,0.707909,0.011013,210,0.725046,0.720818,0.717833,0.720889,0.730275,0.722972,0.004313
1,12.712624,3.940487,2.590621,1.374750,AdaBoostClassifier(algorithm='SAMME'),CountVectorizer(token_pattern=None),0.8,3000,2,"(1, 1)",...,0.709037,0.010830,186,0.725046,0.720818,0.717833,0.721637,0.722256,0.721518,0.002327
2,18.365387,1.379911,4.883941,0.888284,AdaBoostClassifier(algorithm='SAMME'),CountVectorizer(token_pattern=None),0.8,3000,2,"(1, 1)",...,0.717586,0.015627,25,0.735215,0.721939,0.724743,0.722424,0.733068,0.727478,0.005564
3,20.766616,4.046790,2.685077,1.525852,AdaBoostClassifier(algorithm='SAMME'),CountVectorizer(token_pattern=None),0.8,3000,2,"(1, 1)",...,0.717282,0.015782,37,0.735215,0.721939,0.724743,0.722424,0.728960,0.726656,0.004947
4,15.595309,6.251313,1.673674,2.090103,AdaBoostClassifier(algorithm='SAMME'),CountVectorizer(token_pattern=None),0.8,3000,2,"(1, 1)",...,NaN,NaN,288,NaN,NaN,NaN,0.720385,0.725675,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,13.318210,4.399946,3.760446,3.329728,AdaBoostClassifier(algorithm='SAMME'),TfidfVectorizer(token_pattern=None),0.9,None,3,"(1, 2)",...,0.714200,0.014210,79,0.727273,0.729089,0.730140,0.719340,0.734161,0.728001,0.004884
284,20.417262,1.747585,7.995834,1.998785,AdaBoostClassifier(algorithm='SAMME'),TfidfVectorizer(token_pattern=None),0.9,None,3,"(1, 2)",...,0.709257,0.009391,176,0.721053,0.720805,0.740317,0.726480,0.729380,0.727607,0.007144
285,21.979633,6.704985,3.585828,2.264103,AdaBoostClassifier(algorithm='SAMME'),TfidfVectorizer(token_pattern=None),0.9,None,3,"(1, 2)",...,0.721873,0.018379,13,0.744966,0.729659,0.741544,0.727273,0.732268,0.735142,0.006896
286,17.024531,1.292209,4.146189,0.982747,AdaBoostClassifier(algorithm='SAMME'),TfidfVectorizer(token_pattern=None),0.9,None,3,"(1, 2)",...,0.701348,0.014790,264,0.730745,0.721750,0.730139,0.715051,0.725907,0.724718,0.005821
287,10.119639,4.051219,1.580844,0.488251,AdaBoostClassifier(algorithm='SAMME'),TfidfVectorizer(token_pattern=None),0.9,None,3,"(1, 2)",...,0.712297,0.020041,126,0.739709,0.721141,0.730583,0.715476,0.729229,0.727228,0.008321